Improves pack_and_deploy

diff --git a/pack_and_deploy b/pack_and_deploy
--- a/pack_and_deploy
+++ b/pack_and_deploy
@@ -1,15 +1,20 @@
 #!/usr/bin/env bash
 
-if [ -z "$CLOJARS_USERNAME" ]; then
-   echo "CLOJARS_USERNAME is empty"
-fi
-
-if [ -z "$CLOJARS_PASSWORD" ]; then
-   echo "CLOJARS_PASSWORD is empty"
+if [[ $(git diff --stat) != '' ]]; then
+  echo "Error: dirty repo"
+  exit 1
+elif [ -z "$CLOJARS_USERNAME" ]; then
+  echo "Error: CLOJARS_USERNAME is empty"
+  exit 1
+elif [ -z "$CLOJARS_PASSWORD" ]; then
+  echo "Error: CLOJARS_PASSWORD is empty"
+  exit 1
 fi
 
 # Generate pom file
 clj -Spom
+
+sed -i "s/HEAD/$(git rev-parse HEAD)/g" pom.xml
 
 # Generate jar file
 rm -f whiskey.jar
@@ -17,3 +22,5 @@ clj -Apack
 
 # Upload to clojars
 clj -Adeploy
+
+git checkout pom.xml
